# Generated by Django 6.0.1 on 2026-01-21 11:09

import django.core.validators
import django.db.models.deletion
import finder.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('job_field', models.CharField(choices=[('it', 'IT / Software Development'), ('sales', 'Sales & Marketing'), ('finance', 'Finance / Accounting'), ('support', 'Customer Support'), ('hr', 'Human Resources'), ('ops', 'Operations / Logistics'), ('manufacturing', 'Manufacturing'), ('healthcare', 'Healthcare'), ('education', 'Education & Training'), ('design', 'Design / Creative'), ('hospitality', 'Hospitality & Travel'), ('construction', 'Construction / Engineering'), ('gov', 'Government / Public Sector')], max_length=40)),
                ('resume', models.FileField(upload_to=finder.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
