# Generated by Django 6.0.1 on 2026-01-21 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('job_type', models.CharField(max_length=50)),
                ('job_field', models.CharField(choices=[('IT / Software Development', 'IT / Software Development'), ('Sales & Marketing', 'Sales & Marketing'), ('Finance / Accounting', 'Finance / Accounting'), ('Customer Support', 'Customer Support'), ('Human Resources', 'Human Resources'), ('Operations / Logistics', 'Operations / Logistics'), ('Manufacturing', 'Manufacturing'), ('Healthcare', 'Healthcare'), ('Education & Training', 'Education & Training'), ('Design / Creative', 'Design / Creative'), ('Hospitality & Travel', 'Hospitality & Travel'), ('Construction / Engineering', 'Construction / Engineering'), ('Government / Public Sector', 'Government / Public Sector')], max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
